### ISSUE TITLE
作者您好，感谢您的工作和开源贡献，有几个小问题请教

### ISSUE THREAD

**Issue by AllenZYJ** [ma125120/keep_account#1]
我直接拉取下来二次开发好像出了一些问题，不知道能不能指点一二：
flutter后出现：
FAILURE: Build failed with an exception.

* Where:
Script '/Users/zhangyiji/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/zhangyiji/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 41s

**Comment by ma125120** [comment]
这个是构建错误，你打包的安卓？那需要翻墙安装gradle了，你可以百度一下怎么绿色安装这个。

或者你应该是mac吧，可以试试打包成ios应用，应该是没有gradle的问题的

**Comment by AllenZYJ** [comment]
您这个框架有基于空安全吗，还是非空安全版本开发的呢，我这边都是关于null safety的错误

**Comment by AllenZYJ** [comment]
lib/main.dart:65:35: Error: The getter 'generator' isn't defined for the class 'MyRouter'.
 - 'MyRouter' is from 'package:keep_account/router/index.dart' ('lib/router/index.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'generator'.
      onGenerateRoute: App.router.generator,                                                     ^^^^^^^^^                    lib/router/index.dart:34:13: Error: The method 'define' isn't defined for the class 'MyRouter'.
 - 'MyRouter' is from 'package:keep_account/router/index.dart' ('lib/router/index.dart').
Try correcting the name to the name of an existing method, or defining a method named 'define'.
    _router.define(routePath, handler: handler, transitionType: transitionType);
            ^^^^^^                                             ../../flutter/.pub-cache/hosted/pub.dartlang.org/bot_toast-2.4.1/lib/src/key_board_safe_area.dart:12:48: Error: No named parameter with the name 'nullOk'.
    MediaQueryData data= MediaQuery.of(context,nullOk: true);                                                 ^^^^^^          ../../flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {                                     ^^                                                                                                                                                                   FAILURE: Build failed with an exception.                                                                                      * Where:                                                       Script '/Users/zhangyiji/Documents/ibooker/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                               * What went wrong:                                             Execution failed for task ':app:compileFlutterBuildDebug'.     > Process 'command '/Users/zhangyiji/Documents/ibooker/flutter/bin/flutter'' finished with non-zero exit value 1
                                                               * Try:                                                         Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                               * Get more help at https://help.gradle.org                                                                                    BUILD FAILED in 29s
非常感谢您的解答，今天我直接clone下来后直接flutter run出现了这个错误，想请教下这里是因为sdk版本跟您配置文件不对吗，您配置文件的版本有改过吗？期待您的回复，再次感谢～

**Comment by ma125120** [comment]
我更新了一下依赖库，重新clone一下，我这边可以正常run了

**Comment by AllenZYJ** [comment]
非常感谢您的更新～
